Start of a fix for BW's biome-related rituals
DimensionalDevelopment/JustEnoughIDs pull request #153
Opened 2020-08-17 22:50 UTC by Sunconure11

The TC code was fairly identical to what I pretty much needed. Still has a few minor things that need to be worked out, but I'm confident you guys can do that.

What's needed:

Clean up the gradle. The gradle is a byproduct of how I had to bypass some bugs with it, currently.
Biomes changed by shifting seasons need to refresh. The change is registered, but unless one does something like break a block, or log in and out, the color does not change. This does not happen with the blighted lands ritual for some reason.
Test on things such as servers.

2020-08-17 23:29 UTC, Sunconure11 commented
Oddities noted:

Some rites don't fully change a biome in a specific radius. Furthermore, biomes seem to want to change on their own.

2020-08-18 02:07 UTC, BoogieMonster1O1 commented on build.gradle
> +apply plugin: 'com.wynprice.cursemaven'
cursemaven's now a website, not a gradle plugin

2020-08-18 02:20 UTC, Sunconure11 commented on build.gradle
> +apply plugin: 'com.wynprice.cursemaven'
I had to use the plugin just so I could even get a hold of the appropriate curse files. However I can update it, give me tomorrow or so.

2020-08-18 19:35 UTC, Sunconure11 commented
Alright, this seems to work as intended, but in order for one to see the changes, one must relog from a world, or trigger a block update.

2020-08-18 21:05 UTC, Sunconure11 commented
Shifting seasons seems to be fine with the packet on servers. However, blighted lands craps itself.

2020-08-18 22:16 UTC, Sunconure11 commented
Fixed blighted lands. Though I suppose it would crap itself regardless, when you're looking for a lot of blocks to convert at once.

2020-08-18 22:17 UTC, Sunconure11 commented
I'm honestly not too fond of this code, but if anyone thinks they can do better, feel free to do so.

2020-08-19 02:27 UTC, BoogieMonster1O1 requested changes
one small change

2020-08-19 02:27 UTC, BoogieMonster1O1 commented on src/main/java/org/dimdev/jeid/mixin/modsupport/bewitchment/MixinRitualBiomeShift.java
> +    @Overwrite(remap = false)
are you sure you want to overwrite here? There's definitely a better way. 
you could inject at `INVOKE`, shift to `Shift.AFTER` and set the target to the descriptor `setBiome`, and just add 
```
world.getMinecraftServer().getPlayerList().getPlayers().forEach(p -> p.connection.sendPacket(new SPacketChunkData(world.getChunk(effectivePos), 65535)));
```
This will inject right after `setBiome`, which is the only place required to inject.

2020-08-19 03:00 UTC, Sunconure11 commented on src/main/java/org/dimdev/jeid/mixin/modsupport/bewitchment/MixinRitualBiomeShift.java
> +    @Overwrite(remap = false)
Any examples of injection in the code of this mod itself? Fairly new to toying with mixins.

2020-08-19 11:50 UTC, BoogieMonster1O1 commented on src/main/java/org/dimdev/jeid/mixin/modsupport/bewitchment/MixinRitualBiomeShift.java
> +    @Overwrite(remap = false)
until now I've only seen overwrites(which is probably not a good sign) in jeid. 
I do have a cheat sheet about mixins, which you can refer to. 
https://github.com/BoogieMonster1O1/mixincs-updated/blob/master/README.md
You'd want to look at `@At`.

2020-09-04 06:15 UTC, merged

2020-09-04 12:01 UTC, Sunconure11 commented
As per discussion in the discord, this needs a bit more work added on to fully fix it, as I cannot invest more time into this myself.